/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : bigint,
  'status' : string,
  'user' : Principal,
  'timestamp' : Time,
  'items' : Array<OrderItem>,
  'totalPrice' : bigint,
}
export interface OrderItem {
  'size' : string,
  'sneakerId' : bigint,
  'quantity' : bigint,
}
export interface Sneaker {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'sizes' : Array<string>,
  'imageUrl' : string,
  'category' : string,
  'brand' : string,
  'price' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSneaker' : ActorMethod<[Sneaker], bigint>,
  'deleteSneaker' : ActorMethod<[bigint], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllSneakers' : ActorMethod<[], Array<Sneaker>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[bigint], Order>,
  'getSneaker' : ActorMethod<[bigint], Sneaker>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[Array<OrderItem>, bigint], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, string], undefined>,
  'updateSneaker' : ActorMethod<[Sneaker], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];